/*global.number = 0;
global.schadenmodifikator = 0;
global.klettern = ord("W");
global.links = ord("A");
global.rechts = ord("D");
global.ducken = ord("S");
global.springen = vk_space;*/
global.localsound = audio_play_sound(snd_haupmenu, 10, true);
global.roomIndex = room;